name: tiktok_downloader
description: Tiktok Downloader app with flutter

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  chewie: ^1.5.0
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_lints: ^2.0.1
  fluttertoast: ^8.1.1
  gallery_saver: ^2.3.2
  get_it: ^7.2.0
  internet_connection_checker: ^1.0.0+1
  path_provider: ^2.0.11
  permission_handler: ^10.0.1
  video_player: ^2.6.1
  video_thumbnail: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/